[platformio]
default_envs = waveshare_s3
core_dir = .pio-core

[env:waveshare_s3]
platform = espressif32@6.10.0
board = esp32-s3-devkitc-1
framework = arduino
platform_packages =
    platformio/framework-arduinoespressif32@3.20017.0
board_build.mcu = esp32s3
board_build.f_cpu = 240000000L
board_build.flash_mode = qio
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
board_upload.flash_size = 16MB
board_upload.maximum_size = 3145728
board_build.partitions = partitions.csv
monitor_speed = 115200
upload_speed = 460800
build_flags =
    -DBOARD_HAS_PSRAM
    -DARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DLV_CONF_INCLUDE_SIMPLE
    -Iinclude
lib_deps =
    lvgl/lvgl@8.4.0
    moononournation/GFX Library for Arduino@1.5.5
    lewisxhe/SensorLib@0.3.1
    robtillaart/TCA9554@0.1.2
check_tool = cppcheck
check_flags = cppcheck: --enable=warning,performance,portability --suppress=missingIncludeSystem
check_skip_packages = yes
